import { createApp } from "vue";
import Antd from "ant-design-vue";
import router from "./router";
import { createPinia } from "pinia";
import App from "./App.vue";
import "ant-design-vue/dist/reset.css";
import "virtual:uno.css";
import "./_themes.css";
const pinia = createPinia();
createApp(App).use(Antd).use(pinia).use(router).mount("#app");
